#! /usr/bin/env bash
set -euo pipefail

/usr/bin/git pull --ff-only
bundle install
bower install
RAILS_ENV=production /usr/bin/rake db:migrate
RAILS_ENV=production /usr/bin/rake assets:precompile

sudo systemctl restart nginx_passenger.service
